require 'ansi/code'
require 'hipchat-api'
require 'octokit'

require 'cleric/cli'
require 'cleric/cli_configuration_provider'
require 'cleric/console_announcer'
require 'cleric/hipchat_announcer'
require 'cleric/github_agent'
require 'cleric/repo_manager'
